/**
 * EmailBrain - ENHANCED WITH LEARNING
 * Now pulls learned data alongside static config
 * Location: backend/src/emailbrain/EmailBrain.ts
 */

import { NICHE_PROFILES } from '../emailbrain/config/masterConfig.generated'; 
import { StageDetector, EmailEngagementData } from './services/stageDetector';
import { PersonaClassifier, UserProfile } from './services/personaClassifier';
import { BehavioralProfile, initializeBehavioralProfile } from './profiles/BehavioralProfile';
import { BehavioralProfileManager } from './managers/BehavioralProfileManager';

/**
 * Core intelligent context generated by EmailBrain
 */
export interface EmailBrainContext {
  userId: string;
  companyName: string;
  userRole: string;
  companySize: string;
  nicheId: string;
  niche: any;
  
  // === LEARNING DATA ===
  behavioralProfile?: BehavioralProfile;
  learningConfidence?: "low" | "medium" | "high" | "very_high";
  campaignsTracked?: number;
  
  currentStage: 'awareness' | 'consideration' | 'decision' | 'retention';
  topPersona: string;
  personaScore: number;
  engagementMetrics: {
    openRate: number;
    clickRate: number;
    engagementScore: number;
    isActive: boolean;
  };
  
  // === STATIC + LEARNED HYBRID ===
  psychologicalTriggers: string[];
  rankedTriggers: Array<{ trigger: string; score: number }>;
  
  communicationPattern: {
    tone: string;
    languageStyle: string;
    messagingFocus: string;
    formalityLevel: string;
  };
  
  stageFramework: any;
  companySizeProfile: any;
  buyerPersonaProfile: any;
  
  // === LEARNED OVERRIDES (HUMAN-LIKE BEHAVIOR) ===
  learnedBestTrigger?: string;
  learnedBestCTA?: string;
  learnedBestSendTime?: string;
  learnedPersonaAdjustments?: any;
  learnedObjectionPatterns?: any[];
  
  narrativeHooks: string[];
  ctaPatterns: string[];
  ctaType: string;
  urgencySignals: string[];
  subjectLineStyle: string;
  
  predictedObjections: Array<{
    objection: string;
    reframe: string;
    cta: string;
    likelihood: number; // NEW: How likely this objection actually is
  }>;
  
  seasonalContext?: string;
  seasonalUrgency?: string;
  optimalSendTime?: string;
  
  valueLadderTier: string;
  valueLadderOffering: string;
  nextUpselledProduct?: string;
  
  competitivePosition: string;
  competitiveAngle: string;
  
  // === NEW: MARKET INTELLIGENCE ===
  marketSaturation?: number;
  exhaustedMessaging?: string[];
  uniqueAnglesAvailable?: string[];
  
  recommendations: {
    emailFrequency: string;
    contentFocus: string[];
    toneSuggestion: string;
    urgencyLevel: 'low' | 'medium' | 'high' | 'critical';
  };
  
  systemPrompt: string;
}
 
export interface EmailBrainParams {
  userId: string;
  companyName: string;
  userRole: string;
  companySize: string;
  industry: string;
  nicheId: string;
  engagementData: EmailEngagementData;
  behavioralProfile?: BehavioralProfile; // Optional: pass learned data
}

/**
 * Core function to generate intelligent email context
 * NOW INTEGRATES LEARNED BEHAVIORS
 */
export function generateEmailContext(params: EmailBrainParams): EmailBrainContext {
  const {
    userId,
    companyName,
    userRole,
    companySize,
    industry,
    nicheId,
    engagementData,
    behavioralProfile
  } = params;

  // Step 1: Load niche profile
  const niche = NICHE_PROFILES[nicheId];
  if (!niche) {
    throw new Error(`Niche ${nicheId} not found in profiles`);
  }

  // Step 2: Detect current stage
  const currentStage = StageDetector.detectStage(engagementData);
  const stageFramework = niche.email_stage_framework[currentStage];
  const engagementMetrics = StageDetector.calculateEngagementMetrics(engagementData);

  // Step 3: Classify buyer persona
  const userProfile: UserProfile = { userId, companyName, userRole, companySize, industry };
  const personaScores = PersonaClassifier.classifyPersona(userProfile);
  const topPersona = personaScores[0];

  // Step 4: Get company size profile
  const companySizeKey = getCompanySizeKey(companySize);
  const companySizeProfile = niche.company_size_psychology[companySizeKey];

  // Step 5: Get buyer persona profile
  const buyerPersonaProfile = niche.buyer_persona_dna[topPersona?.personaType];

  // === NEW: INTEGRATE LEARNED BEHAVIORS ===
  let learnedBestTrigger: string | undefined;
  let learnedBestCTA: string | undefined;
  let learnedBestSendTime: string | undefined;
  let learnedPersonaAdjustments: any = null;
  let learningConfidence: "low" | "medium" | "high" | "very_high" = "low";

  if (behavioralProfile && behavioralProfile.data_quality.total_campaigns_tracked > 0) {
    // Get best performing trigger
    const bestTrigger = BehavioralProfileManager.getConfidenceWeightedBest(
      behavioralProfile.learned_triggers
    );
    if (bestTrigger && bestTrigger.confidence > 0.5) {
      learnedBestTrigger = bestTrigger.trigger;
    }

    // Get best performing CTA
    const bestCTA = BehavioralProfileManager.getBestPerformer(
      behavioralProfile.learned_cta_performance.filter(
        c => c.persona === topPersona?.personaType
      ),
      'conversionRate'
    );
    if (bestCTA && bestCTA.conversionRate > 0.03) {
      learnedBestCTA = bestCTA.cta;
    }

    // Get best send time
    if (behavioralProfile.learned_send_times.length > 0) {
      learnedBestSendTime = behavioralProfile.learned_send_times[0].time;
    }

    // Get persona micro-adjustments
    if (behavioralProfile.persona_overrides[topPersona?.personaType || '']) {
      learnedPersonaAdjustments =
        behavioralProfile.persona_overrides[topPersona?.personaType || ''];
    }

    learningConfidence = behavioralProfile.data_quality.confidence_level;
  }

  // Step 6: Rank psychological triggers
  const rankedTriggers = rankPsychologicalTriggers(
    niche.psychological_triggers,
    currentStage,
    companySize,
    topPersona?.personaType,
    learnedBestTrigger // Pass learned data to influence ranking
  );

  // Step 7: Predict objections with likelihoods
  const predictedObjections = predictObjectionsWithLikelihoods(
    niche.objection_handling,
    behavioralProfile?.real_objections || [],
    currentStage,
    companySize
  );

  // Step 8: Check seasonal context
  const { seasonalContext, seasonalUrgency } = getSeasonalContext(
    niche.seasonal_psychology,
    currentStage
  );

  // Step 9: Determine value ladder position
  const { valueLadderTier, valueLadderOffering, nextUpselledProduct } =
    getValueLadderPosition(niche.value_ladder, engagementMetrics, currentStage);

  // Step 10: Get competitive positioning
  const competitivePosition = niche.competitive_positioning?.market_positioning;
  const competitiveAngle = competitivePosition?.[`${currentStage}_angle`] || 'value leader';

  // Step 11: Get stage recommendations
  const stageRecommendations = StageDetector.getStageRecommendations(currentStage);

  // Step 12: Determine urgency level
  const urgencyLevel = getUrgencyLevel(currentStage, companySize, engagementMetrics);

  // Step 13: Build enhanced system prompt with learning
  const formattedTriggers = rankedTriggers.map((trigger: string, index: number) => ({
    trigger,
    score: 100 - index * 10
  }));

  const systemPrompt = buildEnhancedSystemPrompt({
    niche,
    stage: currentStage,
    companySize,
    persona: topPersona?.personaType || 'the_pragmatist',
    triggers: formattedTriggers,
    seasonalContext,
    urgencyLevel,
    learnedData: {
      bestTrigger: learnedBestTrigger,
      bestCTA: learnedBestCTA,
      learningConfidence,
      realObjections: behavioralProfile?.real_objections || []
    }
  });

  // Compile context object
  const emailContext: EmailBrainContext = {
    userId,
    companyName,
    userRole,
    companySize,
    nicheId,
    niche,
    
    // Learning data
    behavioralProfile,
    learningConfidence,
    campaignsTracked: behavioralProfile?.data_quality.total_campaigns_tracked || 0,
    
    currentStage,
    topPersona: topPersona?.personaType || 'the_pragmatist',
    personaScore: topPersona?.score || 50,
    engagementMetrics,
    
    psychologicalTriggers: niche.psychological_triggers,
    rankedTriggers: formattedTriggers,
    
    communicationPattern: {
      tone: niche.communication_patterns.tone,
      languageStyle: niche.communication_patterns.language_style,
      messagingFocus: niche.communication_patterns.messaging_focus,
      formalityLevel: niche.communication_patterns.formality_level
    },
    
    stageFramework,
    companySizeProfile,
    buyerPersonaProfile,
    
    // Learned overrides
    learnedBestTrigger,
    learnedBestCTA,
    learnedBestSendTime,
    learnedPersonaAdjustments,
    learnedObjectionPatterns: behavioralProfile?.real_objections,
    
    narrativeHooks: niche.content_strategies.narrative_hooks,
    ctaPatterns: niche.content_strategies.cta_patterns,
    ctaType: stageFramework.cta_type,
    urgencySignals: niche.content_strategies.urgency_signals,
    subjectLineStyle: stageFramework.subject_line_style,
    
    predictedObjections,
    
    seasonalContext,
    seasonalUrgency,
    optimalSendTime: learnedBestSendTime || niche.industry_benchmarks.best_send_times[0],
    
    valueLadderTier,
    valueLadderOffering,
    nextUpselledProduct,
    
    competitivePosition: Object.keys(competitivePosition || {})[0] || 'value_leader',
    competitiveAngle,
    
    marketSaturation: behavioralProfile?.market_intelligence.market_saturation_score,
    exhaustedMessaging: behavioralProfile?.market_intelligence.exhausted_urgency_signals,
    uniqueAnglesAvailable: behavioralProfile?.market_intelligence.unique_angles_available,
    
    recommendations: {
      emailFrequency: stageRecommendations.emailFrequency,
      contentFocus: stageRecommendations.contentType,
      toneSuggestion: stageRecommendations.toneSuggestion,
      urgencyLevel
    },
    
    systemPrompt
  };

  return emailContext;
}

/**
 * Enhanced system prompt that incorporates learning
 */
function buildEnhancedSystemPrompt(params: {
  niche: any;
  stage: string;
  companySize: string;
  persona: string;
  triggers: Array<{ trigger: string; score: number }>;
  seasonalContext?: string;
  urgencyLevel: string;
  learnedData: {
    bestTrigger?: string;
    bestCTA?: string;
    learningConfidence?: string;
    realObjections?: any[];
  };
}): string {
  const {
    niche,
    stage,
    companySize,
    persona,
    triggers,
    seasonalContext,
    urgencyLevel,
    learnedData
  } = params;

  const realObjectionsSection = learnedData.realObjections?.length
    ? `
REAL OBJECTIONS FROM THIS AUDIENCE:
${learnedData.realObjections
  .slice(0, 3)
  .map((obj: any) => `- "${obj.objection_statement}" (appears ${obj.frequency} times)`)
  .join('\n')}

When writing, preempt these specific concerns naturally in the copy.
`
    : '';

  const learnedDataSection =
    learnedData.learningConfidence === 'high' ||
    learnedData.learningConfidence === 'very_high'
      ? `
LEARNED FROM REAL CAMPAIGNS (${learnedData.learningConfidence} confidence):
${
  learnedData.bestTrigger
    ? `- Most effective trigger: ${learnedData.bestTrigger}`
    : ''
}
${learnedData.bestCTA ? `- Best performing CTA: ${learnedData.bestCTA}` : ''}

Use these insights to inform your copy - they're based on real performance data.
`
      : '';

  return `
You are an expert email copywriter who deeply understands the ${niche.niche_name} industry.
Your emails are data-driven, psychologically informed, and tailored to real audience behavior.

COMPANY PROFILE:
- Industry: ${niche.sector}
- Niche: ${niche.niche_name}
- Company Size: ${companySize}
- Buyer Persona: ${persona}

CURRENT STAGE: ${stage.toUpperCase()}
- Focus on: ${niche.email_stage_framework[stage].content_focus}
- CTA Type: ${niche.email_stage_framework[stage].cta_type}

PSYCHOLOGICAL FRAMEWORK:
- Primary Triggers: ${triggers.slice(0, 3).map(t => t.trigger).join(', ')}
- Pain Points: ${niche.pain_points.slice(0, 3).join(', ')}

COMMUNICATION STYLE:
- Tone: ${niche.communication_patterns.tone}
- Formality: ${niche.communication_patterns.formality_level}

URGENCY LEVEL: ${urgencyLevel}
${seasonalContext ? `- SEASONAL CONTEXT: ${seasonalContext}` : ''}

${learnedDataSection}
${realObjectionsSection}

GUIDELINES:
1. Write copy that resonates with this specific persona
2. Use the psychological triggers and pain points above
3. Avoid the communication patterns that fall flat with this audience
4. Address real objections preemptively
5. Keep CTA aligned with the stage (${niche.email_stage_framework[stage].cta_type})
`;
}

/**
 * Predict objections with likelihoods based on learned data
 */
function predictObjectionsWithLikelihoods(
  staticObjectionHandlers: Record<string, any>,
  learnedObjections: any[],
  stage: string,
  companySize: string
): Array<{
  objection: string;
  reframe: string;
  cta: string;
  likelihood: number;
}> {
  const predictions: Array<any> = [];

  if (stage === 'consideration' || stage === 'decision') {
    // First, add learned objections (real data)
    for (const learned of learnedObjections.slice(0, 3)) {
      predictions.push({
        objection: learned.objection_statement,
        reframe: `Address: ${learned.objection_statement}`,
        cta: learned.best_response_cta || 'Learn More',
        likelihood: Math.min(learned.frequency / 10, 1) // Normalize frequency to 0-1
      });
    }

    // Then add static handlers (theoretical)
    for (const [, handler] of Object.entries(staticObjectionHandlers).slice(0, 3)) {
      if (
        !predictions.find((p: any) => p.objection === (handler as any).objection_statement)
      ) {
        predictions.push({
          objection: (handler as any).objection_statement,
          reframe: (handler as any).email_reframe,
          cta: (handler as any).cta_variant,
          likelihood: 0.5 // Default confidence for theoretical objections
        });
      }
    }
  }

  return predictions.slice(0, 3);
}

/**
 * Helper: Rank triggers with learning integration
 */
function rankPsychologicalTriggers(
  allTriggers: string[],
  stage: string,
  companySize: string,
  persona: string,
  learnedBestTrigger?: string
): string[] {
  const stageOrdering: Record<string, Record<string, number>> = {
    awareness: {
      'Curiosity': 1,
      'Security & Trust': 2,
      'Peace of Mind': 3,
      'Financial Freedom': 4
    },
    consideration: {
      'Competitive Comparison': 1,
      'ROI Optimization': 2,
      'Time Efficiency': 3,
      'Risk Mitigation': 4
    },
    decision: {
      'Fear of Loss': 1,
      'Urgency': 2,
      'Exclusivity': 3,
      'Social Proof': 4
    },
    retention: {
      'Success Celebration': 1,
      'Community & Belonging': 2,
      'Wealth Growth': 3,
      'Optimization': 4
    }
  };

  const ordering = stageOrdering[stage] || {};

  // If we have learned best trigger, prioritize it
  let triggers = [...allTriggers];
  if (learnedBestTrigger && triggers.includes(learnedBestTrigger)) {
    triggers = [
      learnedBestTrigger,
      ...triggers.filter(t => t !== learnedBestTrigger)
    ];
  }

  return triggers.sort((a, b) => {
    const scoreA = ordering[a] || 999;
    const scoreB = ordering[b] || 999;
    return scoreA - scoreB;
  });
}

/**
 * Other helper functions remain the same...
 */
function getCompanySizeKey(size: string): string {
  const sizeMap: Record<string, string> = {
    '1-10': 'micro_1_10',
    'micro': 'micro_1_10',
    '11-50': 'small_11_50',
    'small': 'small_11_50',
    '51-200': 'mid_market_51_500',
    '201-500': 'mid_market_51_500',
    '51-500': 'mid_market_51_500',
    'mid_market': 'mid_market_51_500',
    '500+': 'enterprise_501_plus',
    'enterprise': 'enterprise_501_plus'
  };
  return sizeMap[size] || 'small_11_50';
}

function getSeasonalContext(
  seasonalProfiles: Record<string, any>,
  stage: string
): { seasonalContext?: string; seasonalUrgency?: string } {
  const month = new Date().getMonth() + 1;
  const quarter = Math.ceil(month / 3);

  for (const [key, profile] of Object.entries(seasonalProfiles)) {
    if (key.includes(`q${quarter}`)) {
      return {
        seasonalContext: profile.email_angle,
        seasonalUrgency: profile.urgency_level
      };
    }
  }

  return {};
}

function getValueLadderPosition(
  valueLadder: Record<string, any>,
  metrics: any,
  stage: string
): { valueLadderTier: string; valueLadderOffering: string; nextUpselledProduct?: string } {
  let tier = 'entry_level';

  if (metrics.engagementScore > 50 && stage === 'consideration') {
    tier = 'core_product';
  } else if (metrics.engagementScore > 75 && stage === 'decision') {
    tier = 'premium_tier';
  }

  const tierData = valueLadder[tier];
  const tiers = Object.keys(valueLadder);
  const nextTier = tiers[tiers.indexOf(tier) + 1];

  return {
    valueLadderTier: tier,
    valueLadderOffering: tierData?.offering || 'entry-level offering',
    nextUpselledProduct: nextTier ? valueLadder[nextTier]?.offering : undefined
  };
}

function getUrgencyLevel(
  stage: string,
  companySize: string,
  metrics: any
): 'low' | 'medium' | 'high' | 'critical' {
  if (stage === 'decision') {
    return metrics.engagementScore > 75 ? 'critical' : 'high';
  }
  if (stage === 'consideration') {
    return 'high';
  }
  if (stage === 'awareness') {
    return 'low';
  }
  return 'medium';
}